name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.11
  - pip
  - pandas>=1.3.0
  - numpy>=1.21.0,<2.0.0
  - openpyxl>=3.0.0
  - tqdm>=4.64.0
  - regex>=2022.0.0
  - FlagEmbedding
  - jieba
  - openai>=1.0.0
  - transformers
  - sentence-transformers
  # pa 전용
  - scikit-learn>=1.0.0
  - spacy>=3.4.0
  # sa 전용 (pip로 별도 설치 필요)
  # pip install mecab-python3 mecab-ko mecab-ko-dic
  # mecab-ko, mecab-ko-dic, torch/torchvision/torchaudio는 아래 명령으로 별도 설치
  # pip install torch==2.7.1+cu128 torchvision==0.22.1+cu128 torchaudio==2.7.1+cu128 --extra-index-url https://download.pytorch.org/whl/cu128
  # spaCy 모델은 수동 설치 필요
  # python -m spacy download ko_core_news_lg
  # python -m spacy download zh_core_web_lg
